services:
  backend:
    build: ./backend
    ports:
      - "3032:3032" # Expose backend on port 3032
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${BACKEND_PORT}
    restart: unless-stopped
    networks:
      - fitify-network

  frontend:
    build: ./frontend
    ports:
      - "3031:3031" # Expose frontend on port 3031
    environment:
      - API_URL=${API_URL}
      - PORT=${FRONTEND_PORT}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fitify-network

networks:
  fitify-network:
    driver: bridge
