version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" # Expose backend on port 3001
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Expose frontend on port 3000
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - backend
