services:
  backend:
    build: ./backend
    ports:
      - "3032:3032" # Expose backend on port 3032
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3031:3031" # Expose frontend on port 3031
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - backend
